spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: guides
          uri: https://spring.io/
          filters:
            - SetPath=/guides
          predicates:
            - Path=/