spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: guides
          uri: https://spring.io
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
